### ISSUE TITLE
author bio page and link

### ISSUE THREAD

**Issue by mahcloud** [CrabGirl/CrabGirl#5]
Add an author bio page and link to it from the landing page

**Comment by kyro88** [comment]
Here is the excerpt for this page.

Carolyn Hoffert is the mother of three young children, one particularly opinionated tween, and sixteen indoor plants. Back in middle school, she occupied the grey space between rejected and accepted: tolerated. She has first-hand knowledge of the questions and concerns that crop up in young, spirited children who both want to find their own voice but also fit in.

More recently, Carolyn strives to write literature that is compelling and fun. She first wrote Crab Girl as a novel, complete at 40,000 words. While her readers enjoyed the writing, they lamented there wasn’t a graphic novel to go with it. Thus started her journey to tame the fickle beast that is photoshop. Now, she’s proud to offer another medium for her work to come alive and influence the lives of children.

Carolyn holds a B.A. in English from Brigham Young University and continually strives to improve her craft through writing conferences and workshops. She is president of the Wasatch Chapter of the American Night Writers Association and a member of the Society of Children’s Book Writers and Illustrators.

**Comment by kyro88** [comment]
Here is the updated text. I also have the pictures complete for this page. They're saved under finished and have "website" in their titles.

Tiddlywinks [plant picture for top right corner]: Carolyn Hoffert is the mother of three young children, one particularly opinionated tween, and sixteen indoor plants. Back in middle school, she occupied the freeing grey space between rejected and accepted: tolerated. She has first-hand knowledge of the questions and concerns that crop up in young, spirited children who both want to find their own voice but also fit in.

Quest [ book picture for bottom left]: Carolyn’s story doesn’t start like many writers. Rejected from an advanced learning course when she was younger because she failed the creativity portion of the test, she spent most of her life believing she wasn’t creative enough to be an author or illustrator. It wasn’t until she finished college and had children of her own that her imagination took over. Telling stories to her children and watching their faces light up as they shared those same stories with their friends inspired Carolyn to give writing those stories down a try. Now, she makes time every day to flex her brain and write literature that is compelling and fun. 
Crab Girl, in particular, started as a novel, complete at 40,000 words. She noticed that while her readers loved the story, a majority ended up either describing the fun of how Annie’s claw would work, how Jack’s features looked, or just drawing their own version and asking Carolyn to draw hers so they could compare. Thus started her journey to tame the fickle dual-headed beast that is photoshop and InDesign and give her words illustrated life. Now, she’s proud to offer another medium for her work to come alive and influence the lives of children.

Art [paintbrush/pencil for bottom right]: Carolyn favors bold lines, simple designs, and rich colors. While her drawings hold their own in black and white, she feels the vibrancy of the colors help the richness of her stories pop. She aims to provide drawings that are consistent and reproducible, not just for herself, but for her readers. She wants all kids to believe they can make their dreams come true because they’re willing to try something, not because they’re the best at it.

Street Cred [sunglasses top left]: Carolyn holds a B.A. in English from Brigham Young University and continually strives to improve her craft through writing conferences and workshops. She is president of the Wasatch Chapter of the American Night Writers Association and a member of the Society of Children’s Book Writers and Illustrators.
